name: static
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Credentials
        uses: actions/checkout@v5
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
